# This is an environment for hhnk_qgis_plugin installation
name: threedipy

channels:
  - conda-forge
  - defaults

dependencies:
  #QGIS preinstalled
  - python=3.9.5 # equals MI python version
  - geopandas=0.12.2
  - pandas=1.1.3
  - scipy=1.6.2

  # - attrs=22.2.0
  # - apscheduler=3.10.1
  # - click=8.1.3
  # - click-plugins=1.1.1
  # - colorama=0.4.6
  # - exceptiongroup=1.1.1
  # - iniconfig=2.0.0
  # - ipyfilechooser=0.6.0
  # - jupyter=1.0.0
  # - geoalchemy2=0.10.2
  # - tomli=2.0.1
  # - tzlocal=2.1
  # - packaging=23.0
  # - python-dateutil=2.8.2
  # - pytz=2020.1
  # - pytz-deprecation-shim=0.1.0.post0
  # - sqlalchemy=1.3.24

  #User folder
  - jupyterlab=3.6.3
  - ipywidgets=8.0.6
  - pytest=7.2.2
  - pytest-cov
  - pluggy=1.0.0 #pytest dependency
  - exceptiongroup=1.1.1 #pytest dependency
  - iniconfig=2.0.0 #pytest dependency
  - tqdm=4.64.0
  - xarray=2022.3.0
  # - pygeos=0.14 #required for geopandas, not for geopandas 0.12.2

  #Voor DataCheker
  - flask # oude datachecker
  - sqlparse # oude datachecker
  - psycopg2 # oude datachecker
  - fastapi # nieuwe datachecker
  - uvicorn # nieuwe datachecker

  #Voor Daniel
  - spyder
  - pip: # 3Di packages are not conda installable and are therefore installed by PIP
    # - et-xmlfile==1.1.0 needed where?
    - openpyxl==3.1.2
    - threedi_modelchecker==2.2.4 #ThreediToolbox 2.5.3
    - threedi_scenario_downloader==1.2 #Lizard API v4 only
    - threedi_schema==0.217.6 #ThreediToolbox 2.5.4
    # - threedi_raster_edits==0.26 #deprecate?
    - threedi-api-client==4.1.2 #3Di Models and Simulations 3.5.2
    - threedigrid_builder==1.11.4 #ThreediToolbox 2.5.3
    - threedigrid==2.0.6 #ThreediToolbox 2.5.4
    - threedidepth==0.6.1 #ThreediToolbox 2.5.4
    - cached_property==1.5.2 #threedi_raster_edits dep
    - rtree==1.0.1 #threedi_raster_edits dep 
    # - h5py==2.10.0 #Works with gdal but build wheel doesnt work