# """This is an environment for conda environment on ota155 and srv514
# Can be used as standalone env where the following utils should work:
# - hhnk-threedi-tools
# - hhnk-research-tools
# - datachecker
# - modelbuilder
#
# threedi and research-tools should be installed manually to use the
# latest dev version. Do this by pulling the github branch and running
# bin/install_local.bat in those branches.
# """
name: threedipy_p312

channels:
  - conda-forge

dependencies:
  - python=3.12.10 # equals MI python version

  # NenS Deps https://github.com/nens/nens-dependency-loader/blob/main/dependencies.py
  # - alembic==1.14.*
  # - certifi
  # - cftime>=1.5.0  # threedigrid[results]
  # - click>=8.0,<8.2
  # - colorama  # dep of click and threedi-modelchecker (windows)
  # - condenser>=0.2.1
  # - dateutil
  # - geoalchemy2==0.15.*
  # - greenlet!=0.4.17
  # - h5netcdf
  # - h5py==3.10.0
  # - hydxlib==1.7.3
  # - importlib_resources  # backward compat. alembic
  # - jwt  # for PyJWT
  # - mako
  # - networkx
  # - packaging
  # - pyqtgraph>=0.13.2
  # - requests
  # - shapely>=2.0.0
  # - six
  # - sqlalchemy==2.0.6
  # - typing_extensions>=4.2.0
  # - urllib3
  # - zipp  # backward compat. alembic

  # MI 3.40 site packages
  - scipy==1.13.0
  - geopandas==1.0.1
  - pandas==2.2.2
  - openpyxl #3.1.2
  - numpy==1.26.4

  # HHNK Deps
  - jupyterlab
  - ipywidgets
  - jupytext
  - pytest
  - pytest-cov
  - tqdm
  - xarray
  - cached_property
  - rtree
  - rioxarray
  - pyogrio
  # - rasterio #rxr dep
  # - affine #rxr dep
  # - dask #rxr dep
  # See also: https://discourse.matplotlib.org/t/latest-versions-via-pip-jupyterlab-import-of-matplotlib-broken/24477/7
  - matplotlib  #3.9.0 gives RuntimeError: Entry point name 'inline' duplicated
  - folium
  # - branca #folium dep
  # - xyzservices #folium dep
  - oracledb
  - seaborn
  - rasterstats
  - ruff
  - gdal

  # Voor DataCheker
  - flask # oude datachecker
  - sqlparse # oude datachecker
  - psycopg2 # oude datachecker
  - fastapi # nieuwe datachecker
  - uvicorn # nieuwe datachecker
  - django<4 # datachecker (<4 wegens compatibility met 3Di modules)


  - pip
  - pip:
    - threedi-api-client==4.1.12
    - threedi-modelchecker==2.18.3
    - threedi-schema==0.300.26
    - threedi-scenario-downloader
    - threedi_mi_utils==0.1.10
    - threedigrid==2.3.5
    - threedigrid-builder>=1.24.3
    - threedidepth==0.6.3


  # Install these with bin/install_local.bat
  # - hhnk_research_tools==2024.1
  # - hhnk_threedi_tools==2024.1
