# """This is an environment for conda environment on ota155 and srv514
# Can be used as standalone env where the following utils should work:
# - hhnk-threedi-tools
# - hhnk-research-tools
# - datachecker
# - modelbuilder
#
# threedi and research-tools should be installed manually to use the
# latest dev version. Do this by pulling the github branch and running
# bin/install_local.bat in those branches.
# """
name: threedipy

channels:
  - conda-forge

dependencies:
  #QGIS preinstalled
  - python=3.9.18 # equals MI python version
  - geopandas=0.14.1
  - fiona=1.9.5 # higher versions dont work with geopandas < 0.14.4
  - pandas=2.0.2
  - scipy=1.10.1
  # - h5py=3.8.0 # incompatible met rest van env; conda solved naar 3.11.0

  #User folder
  - jupyterlab=4.2.0
  - ipywidgets=8.1.2
  #External deps plugin
  - pytest=7.2.2
  - pytest-cov
  - pluggy=1.0.0 #pytest dependency
  # - exceptiongroup=1.1.1 #pytest dependency
  - iniconfig=2.0.0 #pytest dependency
  - tqdm=4.64.0
  - xarray=2024.3.0
  - openpyxl=3.1.2
  - cached_property=1.5.2
  - rtree=1.0.1
  - rioxarray=0.15.0 #higher versions need python >=3.10
  - pyogrio=0.10.0
  - rasterio=1.3.10 #rxr dep, 1.4.3 breaks with current proj
  - affine=2.4.0 #rxr dep
  - dask=2024.6.2 #rxr dep
  - matplotlib=3.5.1 #3.9.0 gives RuntimeError: Entry point name 'inline' duplicated
  - oracledb=2.4.1
  # See also: https://discourse.matplotlib.org/t/latest-versions-via-pip-jupyterlab-import-of-matplotlib-broken/24477/7


  #Voor DataCheker
  - flask # oude datachecker
  - sqlparse # oude datachecker
  - psycopg2 # oude datachecker
  - fastapi # nieuwe datachecker
  - uvicorn # nieuwe datachecker
  - django<4 # datachecker (<4 wegens compatibility met 3Di modules)
  - pip=24.0

  - pip: # 3Di packages are not conda installable and are therefore installed by PIP
    - threedi_modelchecker==2.6.3 #threedi_results_analysis 3.9.0
    - threedi_scenario_downloader==1.4 #Lizard API v4 only
    - threedi_schema==0.219.3 #threedi_results_analysis 3.9.0
    - threedi-api-client==4.1.7 #3Di Models and Simulations 3.11.0
    - threedigrid_builder==1.14.4 #threedi_results_analysis 3.9.2
    - threedigrid==2.3.3 #threedi_results_analysis 3.12.0
    - threedigrid==2.2.11 #threedi_results_analysis 3.9.3
    - threedidepth==0.6.3 #threedi_results_analysis 3.9.0


  # Install these with bin/install_local.bat
  # - hhnk_research_tools==2024.1
  # - hhnk_threedi_tools==2024.1
