# """This is an environment for conda environment on ota155 and srv514
# Can be used as standalone env where the following utils should work:
# - hhnk-threedi-tools
# - hhnk-research-tools
# - datachecker
# - modelbuilder
#
# threedi and research-tools should be installed manually to use the
# latest dev version. Do this by pulling the github branch and running
# bin/install_local.bat in those branches.
# """
name: threedipy

channels:
  - conda-forge
  - defaults

dependencies:
  #QGIS preinstalled
  - python=3.9.18 # equals MI python version
  - geopandas=0.14.1
  - pandas=2.0.2
  - scipy=1.10.1
  - h5py=3.8.0 # incompatible met rest van env; conda solved naar 3.11.0

  #User folder
  - jupyterlab=4.2
  - ipywidgets=8.1.2
  #External deps plugin
  - pytest=7.2.2
  - pytest-cov
  - pluggy=1.0.0 #pytest dependency
  # - exceptiongroup=1.1.1 #pytest dependency
  - iniconfig=2.0.0 #pytest dependency
  - tqdm=4.64.0
  - xarray=2024.3.0
  - openpyxl=3.1.2
  - cached_property=1.5.2
  - rtree=1.0.1
  - pyogrio

  #Voor DataCheker
  - flask # oude datachecker
  - sqlparse # oude datachecker
  - psycopg2 # oude datachecker
  - fastapi # nieuwe datachecker
  - uvicorn # nieuwe datachecker
  - django<4 # datachecker (<4 wegens compatibility met 3Di modules)

  - pip: # 3Di packages are not conda installable and are therefore installed by PIP
    - threedi_modelchecker==2.4.0 #ThreediToolbox 2.5.5


    - threedi_scenario_downloader==1.4 #Lizard API v4 only
    - threedi_schema==0.217.11 #ThreediToolbox 2.5.4

    - threedi-api-client==4.1.4 #3Di Models and Simulations 3.6.1
    - threedigrid_builder==1.12.1 #ThreediToolbox 2.5.5
    - threedigrid==2.0.6 #ThreediToolbox 2.5.4
    - threedidepth==0.6.1 #ThreediToolbox 2.5.4