site_name: HHNK 3Di toolbox
site_url: https://threedi.github.io/hhnk-threedi-plugin/
theme:
  name: "material"
  language: en
  logo: icons/hhnk_logo_white.png
  favicon: icons/hhnk_logo.png
  highlightjs: true
  palette:
    - scheme: hhnk
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
extra_css:
- stylesheets/extra.css
- stylesheets/headings.css

plugins:
  - search
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/threedi/hhnk-threedi-plugin
nav:
    - Home: docs/index.md
    - Installatie Instructies: docs/md_files/installation_manual.md
    - Gebruikershandleiding: md_files/usage.md
    - Bron data: md_files/needed_data.md
    - Polder clusters: md_files/polder_clusters.md
    - Uitleg tests en functionaliteit: md_files/tests_documentation.md
