# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelselection_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ModelSelectionDialogBase(object):
    def setupUi(self, ModelSelectionDialogBase):
        ModelSelectionDialogBase.setObjectName("ModelSelectionDialogBase")
        ModelSelectionDialogBase.resize(1014, 873)
        ModelSelectionDialogBase.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.gridLayout = QtWidgets.QGridLayout(ModelSelectionDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(ModelSelectionDialogBase)
        self.frame.setMinimumSize(QtCore.QSize(484, 222))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setObjectName("username")
        self.horizontalLayout.addWidget(self.username)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password.setObjectName("password")
        self.horizontalLayout_2.addWidget(self.password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.login = QtWidgets.QPushButton(self.frame)
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        spacerItem2 = QtWidgets.QSpacerItem(5, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 2)
        self.button_box = QtWidgets.QDialogButtonBox(ModelSelectionDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 15, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(ModelSelectionDialogBase)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout.addWidget(self.frame_3, 11, 1, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 14, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(ModelSelectionDialogBase)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_4.addWidget(self.listWidget)
        self.listView = QtWidgets.QListView(self.frame_2)
        self.listView.setObjectName("listView")
        self.horizontalLayout_4.addWidget(self.listView)
        self.gridLayout.addWidget(self.frame_2, 6, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(ModelSelectionDialogBase)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 13, 1, 1, 1)

        self.retranslateUi(ModelSelectionDialogBase)
        self.button_box.accepted.connect(ModelSelectionDialogBase.accept)
        self.button_box.rejected.connect(ModelSelectionDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(ModelSelectionDialogBase)

    def retranslateUi(self, ModelSelectionDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ModelSelectionDialogBase.setWindowTitle(_translate("ModelSelectionDialogBase", "HHNK"))
        self.label.setText(_translate("ModelSelectionDialogBase", "User name"))
        self.label_2.setText(_translate("ModelSelectionDialogBase", "Password  "))
        self.login.setText(_translate("ModelSelectionDialogBase", "Log In"))

