# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hhnk_toolbox_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HHNK_toolboxDockWidget(object):
    def setupUi(self, HHNK_toolboxDockWidget):
        HHNK_toolboxDockWidget.setObjectName("HHNK_toolboxDockWidget")
        HHNK_toolboxDockWidget.resize(489, 683)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HHNK_toolboxDockWidget.sizePolicy().hasHeightForWidth())
        HHNK_toolboxDockWidget.setSizePolicy(sizePolicy)
        HHNK_toolboxDockWidget.setMinimumSize(QtCore.QSize(205, 534))
        HHNK_toolboxDockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        HHNK_toolboxDockWidget.setBaseSize(QtCore.QSize(0, 0))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.dockWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.server_btn = QtWidgets.QPushButton(self.tab_1)
        self.server_btn.setGeometry(QtCore.QRect(0, 220, 411, 23))
        self.server_btn.setObjectName("server_btn")
        self.model_state_show = QtWidgets.QLabel(self.tab_1)
        self.model_state_show.setGeometry(QtCore.QRect(0, 100, 790, 13))
        self.model_state_show.setObjectName("model_state_show")
        self.model_state_label = QtWidgets.QLabel(self.tab_1)
        self.model_state_label.setGeometry(QtCore.QRect(0, 80, 790, 13))
        self.model_state_label.setObjectName("model_state_label")
        self.load_layers_btn = QtWidgets.QPushButton(self.tab_1)
        self.load_layers_btn.setGeometry(QtCore.QRect(0, 50, 401, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_layers_btn.sizePolicy().hasHeightForWidth())
        self.load_layers_btn.setSizePolicy(sizePolicy)
        self.load_layers_btn.setObjectName("load_layers_btn")
        self.create_new_project_btn = QtWidgets.QPushButton(self.tab_1)
        self.create_new_project_btn.setGeometry(QtCore.QRect(0, 20, 541, 23))
        self.create_new_project_btn.setObjectName("create_new_project_btn")
        self.model_state_btn = QtWidgets.QPushButton(self.tab_1)
        self.model_state_btn.setEnabled(False)
        self.model_state_btn.setGeometry(QtCore.QRect(0, 120, 378, 23))
        self.model_state_btn.setObjectName("model_state_btn")
       
        self.lizard_api_key_textbox = QtWidgets.QLineEdit(self.tab_1)
        self.lizard_api_key_textbox.setGeometry(QtCore.QRect(10, 180, 378, 20))
        self.lizard_api_key_textbox.setObjectName("lizard_api_key_textbox")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tests_toolbox = QtWidgets.QToolBox(self.tab_2)
        self.tests_toolbox.setEnabled(False)
        self.tests_toolbox.setGeometry(QtCore.QRect(0, 20, 441, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tests_toolbox.sizePolicy().hasHeightForWidth())
        self.tests_toolbox.setSizePolicy(sizePolicy)
        self.tests_toolbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tests_toolbox.setObjectName("tests_toolbox")
        self.tests_toolboxPage1_2 = QtWidgets.QWidget()
        self.tests_toolboxPage1_2.setGeometry(QtCore.QRect(0, 0, 441, 344))
        self.tests_toolboxPage1_2.setObjectName("tests_toolboxPage1_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tests_toolboxPage1_2)
        self.gridLayout.setObjectName("gridLayout")
        self.sqlite_checks_frame = QtWidgets.QFrame(self.tests_toolboxPage1_2)
        self.sqlite_checks_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sqlite_checks_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sqlite_checks_frame.setLineWidth(0)
        self.sqlite_checks_frame.setObjectName("sqlite_checks_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sqlite_checks_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addWidget(self.sqlite_checks_frame, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.start_sqlite_check_2 = QtWidgets.QPushButton(self.tests_toolboxPage1_2)
        self.start_sqlite_check_2.setMaximumSize(QtCore.QSize(16777215, 23))
        self.start_sqlite_check_2.setObjectName("start_sqlite_check_2")
        self.gridLayout.addWidget(self.start_sqlite_check_2, 1, 0, 1, 1)
        self.tests_toolbox.addItem(self.tests_toolboxPage1_2, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        HHNK_toolboxDockWidget.setWidget(self.dockWidgetContents)
        self.retranslateUi(HHNK_toolboxDockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HHNK_toolboxDockWidget)
      

    def retranslateUi(self, HHNK_toolboxDockWidget):
        _translate = QtCore.QCoreApplication.translate
        HHNK_toolboxDockWidget.setWindowTitle(_translate("HHNK_toolboxDockWidget", "HHNK Toolbox"))
        self.server_btn.setText(_translate("HHNK_toolboxDockWidget", "Open Jupyter Notebook Server"))
        self.model_state_show.setText(_translate("HHNK_toolboxDockWidget", "Onbekend"))
        self.model_state_label.setText(_translate("HHNK_toolboxDockWidget", "Huidige modelstaat:"))
        self.load_layers_btn.setText(_translate("HHNK_toolboxDockWidget", "Laad lagen"))
        self.create_new_project_btn.setText(_translate("HHNK_toolboxDockWidget", "Nieuw project aanmaken"))
        self.model_state_btn.setText(_translate("HHNK_toolboxDockWidget", "Modelstaat aanpassen"))
        self.lizard_api_key_textbox.setText(_translate("HHNK_toolboxDockWidget", "Vul hier je Lizard API key in!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("HHNK_toolboxDockWidget", "Tab 1"))
        self.start_sqlite_check_2.setText(_translate("HHNK_toolboxDockWidget", "Sqlite tests"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("HHNK_toolboxDockWidget", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("HHNK_toolboxDockWidget", "Tab 3"))
        # self.label.setText(_translate("modelSplitterDialog", "User name"))
        # self.label_2.setText(_translate("modelSplitterDialog", "Password  "))
        # self.login.setText(_translate("modelSplitterDialog", "Log In"))
 