name: zip-on-release
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Switch to plugin folder
    - run: |
        cd hhnk_threedi_plugin
        ls -la
    - name: Zip Folder
      run: zip -r hhnk-threedi-plugin.zip . -x ".ipynb_checkpoints/*" ".__pycache__/*" ".external-dependencies/*"
    - name: Release to Github
      run: echo "Release"